### PR TITLE
Fix add command

### LINKED ISSUE #74: Missing prefix for NRIC in add -o and Missing prefix for pet patient name in add -p
#67

### LINKED ISSUE #81: Several Bugs in Add Command
These are the bugs relating to logic that I have found when testing Medeina's storage functions. I have yet to figure out the sources of these bugs as I am not that familiar with the logic part of AddComamnd and was also more focused on getting storage and conversion from XML to Objects and vice versa to work. Please help to resolve if you know where the sources of error are at.

- After typing the following invalid command, no errors pop up, no response from the application whatsoever - should show "NRIC invalid" or some other message (UX + logic problem). But pet does not get added to database (as expected).
`add -p n/Jay s/Cat b/Persian c/Black bt/AB -o S3948923489234`

- Somehow calls up "Person names should only contain alphanumeric characters and spaces, and it should not be blank" upon executing the following command. However, in `PetPatientName` class, the correct string has already been specified in `MESSAGE_PET_NAME_CONSTRAINTS`; uncertain why it will call `MESSAGE_NAME_CONSTRAINTS` from the `Person` class instead.
`add -p n/J@y s/Cat b/Persian c/Black bt/A -o S1234577A`

- Upon executing the following command, there is _no output telling the user that the appointment has been successfully added_ (i.e. command keyed in is not cleared; looks like as if nothing happened). However, if executed again, only then will the user know that the command has been successfully executed **previously** and the appointment has been added, since the output now shows that a duplicate appointment exists.
`add -a d/2018-12-30 12:30 r/nil t/checkup -o S7654321A -p Jay`

Refer to Issue #67 .

### LINKED ISSUE #83: MissingFormatArgumentException in AddCommand.java
image

Identified the problem and the required fix:
image

This bug will be fixed in my next pull request

#67

### LINKED ISSUE #84: Nric is not unique, persons with same nric can be added
If nric is not unique:

- unable to tell which person object to add a new pet patient under (by default, placed under the first person object found with the specified nric)

- cannot tell which particular owner has made a particular appointment (since we keep track of appointments using owner nric)

- doesn't make sense at all for different persons to have the same nric

#67

### PR DESCRIPTION
**Pull request by Aquarinte**
- Updated parsing method for person name and pet patient name to standardize the capitalization of the first character of every word (user input for person name and pet patient name are now case-insensitive)

- Implemented DuplicateNricException to maintain uniqueness of Nric in existing person object list

- Some code refactoring for AddCommand.java

- Updated CLISyntax to standardize naming of prefix variables

- Updated relevant Junit tests

- Fixed many bugs

Fixes #74 
Fixes #81 
Fixes #83 
Fixes #84

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/AddCommand.java [hunk 1]
```diff
@@ -2,46 +2,80 @@
...
 import seedu.address.model.appointment.exceptions.DuplicateAppointmentException;
 import seedu.address.model.person.Nric;
 import seedu.address.model.person.Person;
+import seedu.address.model.person.exceptions.DuplicateNricException;
 import seedu.address.model.person.exceptions.DuplicatePersonException;
 import seedu.address.model.petpatient.PetPatient;
 import seedu.address.model.petpatient.PetPatientName;
 import seedu.address.model.petpatient.exceptions.DuplicatePetPatientException;
 
+//@@ aquarinte
```
Comment (chialejing) [inline src/main/java/seedu/address/logic/commands/AddCommand.java]: @Aquarinte Incorrect format for collate, please remember to change on your end! Should be `//@@ author <username>` instead.

Comment (Aquarinte) [reply src/main/java/seedu/address/logic/commands/AddCommand.java]: Thanks for the heads-up! Will amend in my next pr

Comment (chialejing) [reply src/main/java/seedu/address/logic/commands/AddCommand.java]: :+1:
